version: '3'
services:
    todo:
        build: ./todo
        ports:
            - '8010:8010'
    user:
        build: ./user
        ports:
            - '8020:8020'
    ui:
        build: ./ui
        ports:
            - '3000:3000'
    apigateway:
        build: ./apigateway
        ports:
            - '8030:8030'
        environment:
            TODO_URL: "http://todo:8010"
            USER_URL: "http://user:8020"
        depends_on:
            - todo
            - user
